spring:
  application:
    name: circuit-breaker-service

server:
  port: 8081

resilience4j:
  circuitbreakers:
    countBasedCBName: countBasedCB

management:
  metrics:
    enable:
      disk: false
      executor: false
      http: false
      process: false
      system: false
      jvm: false
      gc: false
      tomcat: false
      application: false
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  defaults:
    metrics:
      export:
        enabled: true